<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUuzx2xs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUuzx2xs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUuzx2xs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUuzx2xs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUuzx2xs\appProdProjectContainer([
    'container.build_hash' => 'Uuzx2xs',
    'container.build_id' => '1b275d00',
    'container.build_time' => 1631367447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUuzx2xs');
